Error message rate limit
ScilifelabDataCentre/dds_web pull request #1034
Opened 2022-03-09 12:02 UTC by zishanmirza

Rate limit: Error message

This patch displays an error message when the user makes too many authentication requests.

Fixes #1024.

- [X] Tests passing
- [X] Black formatting
- [ ] Migrations for any changes to the database schema
- [X] Rebase/merge the `dev` branch
- [ ] Note in the CHANGELOG

2022-03-09 12:43 UTC, inaod568 requested changes

2022-03-09 12:43 UTC, inaod568 commented on dds_web/templates/error.html
> +{% else %}
```suggestion
{% if error_code == 429 %}
    Too many authentication requests in one hour. Try again in a while.
{% else %}
```

2022-03-09 13:26 UTC, zishanmirza commented on dds_web/templates/error.html
> +{% else %}
I have updated the error message.

2022-03-09 15:22 UTC, inaod568 commented
@zishanmirza Can you add a row in the changelog?

2022-03-10 19:11 UTC, zishanmirza commented
I have updated CHANGELOG.md.

2022-03-11 09:07 UTC, inaod568 approved these changes

2022-03-11 10:29 UTC, merged