Update text
ScilifelabDataCentre/dds_web pull request #1062
Opened 2022-03-16 12:40 UTC by zishanmirza

This patch updates switches "Owner" with "Researcher" and updates the text.

- [X] Tests passing
- [X] Black formatting
- [ ] Migrations for any changes to the database schema
- [X] Rebase/merge the `dev` branch
- [ ] Note in the CHANGELOG

2022-03-16 12:42 UTC, zishanmirza commented
Fixes https://github.com/ScilifelabDataCentre/dds_cli/issues/345.

2022-03-16 14:11 UTC, inaod568 commented on dds_web/api/user.py
> +            f"{str(whom)} was associated to the {str(project)} as a Researcher={is_owner}."
Ah, actually what I meant is something like this: (removing the {is_owner} part)

```suggestion
            f"{str(whom)} was associated to the {str(project)} as a {'Project Owner' if is_owner else 'Researcher'}."
```

2022-03-16 14:12 UTC, inaod568 commented on dds_web/api/user.py
> +                f"{str(project)} as a Researcher={is_owner}. An e-mail notification has{' not ' if not send_email else ' '}been sent."
Same here
```suggestion
                f"{str(project)} as a {'Project Owner' if is_owner else 'Researcher'}. An e-mail notification has{' not ' if not send_email else ' '}been sent."
```

2022-03-16 14:14 UTC, inaod568 commented on tests/test_project_status.py
> +        assert "associated to the Project" in x
```suggestion
        assert "given access to the Project" in x
```

2022-03-16 14:15 UTC, inaod568 requested changes
A few changes to remove the "={}" part

2022-03-17 07:02 UTC, inaod568 approved these changes

2022-03-17 07:03 UTC, inaod568 commented
Looks good!

2022-03-17 07:03 UTC, merged