Unit Admin
ScilifelabDataCentre/dds_web pull request #1142
Opened 2022-04-07 09:42 UTC by zishanmirza

This patch adds Unit Admins.

Fixes #1120.

- [X] Tests passing
- [X] Black formatting
- [ ] Migrations for any changes to the database schema
- [X] Rebase/merge the `dev` branch
- [ ] Note in the CHANGELOG

2022-04-07 13:44 UTC, inaod568 requested changes

2022-04-07 13:44 UTC, inaod568 commented on dds_web/development/db_init.py
> +    unit_1.users.extend([unituser_1, unituser_2, unitadmin_1, unitadmin_2, unitadmin_3])
Can you move these up to before the unit is defined? 
In the following way: 
```
    # Create first unit user
    unituser_1 = models.UnitUser(
        username="unituser_1",
        password=password,
        name="First Unit User",
    )
    # email for unituser_1 defined where
    # connect email to unituser_1

    # Create second unit user
    unituser_2 = models.UnitUser(
        username="unituser_2",
        password=password,
        name="Second Unit User",
    )
    # email for unituser_2 
    # connect email to unituser_2

    unitadmin_1 = models.UnitUser(...)
    # email for unitadmin_1
    # connect email to unitadmin_1

    # etc.....
```
And also, set the `active` when defining the users (within the parenthesis), and the same for is_admin for those that are admins.

2022-04-08 08:31 UTC, zishanmirza commented
I have updated the Unit Admins and the Unit Users.

2022-04-08 09:32 UTC, inaod568 approved these changes
Great!

2022-04-08 09:32 UTC, merged