Delete Invite
ScilifelabDataCentre/dds_web pull request #1147
Opened 2022-04-08 15:01 UTC by zishanmirza

This patch deletes invites that are older than a week.

- [X] Tests passing
- [X] Black formatting
- [X] Migrations for any changes to the database schema
- [X] Rebase/merge the `dev` branch
- [] Note in the CHANGELOG

2022-04-11 08:05 UTC, inaod568 requested changes
Looks good, a few comments though. 
Apart from this, could you also keep track of the non-deleted invites in a similar way as the other scheduled tasks? So have a dict that you put the invite errors in and afterward print them out. If there's an issue with one of the invite deletions it should still be possible to delete the others. 

So there should be 2 try-except blocks, one outside of the for loop and one per commit.

2022-04-11 08:05 UTC, inaod568 commented on dds_web/scheduled_tasks.py
> +                    models.ProjectInviteKeys.query.filter_by(invite_id=invite.id).delete()
The db constraints actually handle the `ProjectInviteKeys` so all you need to do is this and both the invites and the rows in the `ProjectInviteKeys` connected to that invite should be deleted.
```suggestion
                    db.session.delete(invite)
```

2022-04-11 09:24 UTC, zishanmirza commented
I have updated the `if` statement, added a `try` statement, and included `errors`.

2022-04-11 09:25 UTC, zishanmirza commented
I have updated the `if` statement, added a `try` statement, and included `errors`.

2022-04-11 09:26 UTC, zishanmirza commented
I have updated the `if` statement, added a `try` statement, and included `errors`.

2022-04-11 11:03 UTC, inaod568 requested changes

2022-04-11 12:05 UTC, zishanmirza commented
I have updated `expiration`.

2022-04-11 12:06 UTC, zishanmirza commented
I have updated `expiration`.

2022-04-11 15:04 UTC, inaod568 requested changes
There was one tiny typo and also we need to save the error message and print that out. Also shouldn't raise in the inner try except, otherwise it will not continue with the next invite.

2022-04-11 15:04 UTC, inaod568 commented on dds_web/scheduled_tasks.py
> +            scheduler.app.logger.error(f"{errors[error]} not deleted.")
```suggestion
        for inv, error in errors.items():
            scheduler.app.logger.error(f"{inv} not deleted: {error}")
```

2022-04-12 07:50 UTC, inaod568 approved these changes
Looks good!

2022-04-12 08:02 UTC, merged