Bug: Checks for invalid characters when creating unit
ScilifelabDataCentre/dds_web pull request #1154
Opened 2022-04-12 11:26 UTC by inaod568

- [ ] Tests passing
- [ ] Black formatting
- [ ] Migrations for any changes to the database schema
- [ ] Rebase/merge the `dev` branch
- [ ] Note in the CHANGELOG

2022-04-12 11:28 UTC, inaod568 commented on dds_web/__init__.py
> +import marshmallow
```suggestion
```

2022-04-12 17:46 UTC, talavis requested changes

2022-04-12 17:46 UTC, talavis commented on dds_web/database/models.py
> +    public_id = db.Column(db.String(50), unique=True, nullable=False)
Isn't this a db change, i.e. a migration is needed?

2022-04-12 17:46 UTC, talavis commented on dds_web/__init__.py
> +    elif public_id[:4] == "xn--":
public_id.startswith() should also work. I don't think it really matters as it's such a minor copy operation.

2022-04-13 06:41 UTC, talavis approved these changes

2022-04-13 07:06 UTC, merged