List Invites endpoint
ScilifelabDataCentre/dds_web pull request #1294
Opened 2022-10-06 19:26 UTC by talavis

> **Before submitting the PR, please go through the sections below and fill in what you can. If there are any items that are irrelevant for the current PR, remove the row. If a relevant option is missing, please add it as an item and add a PR comment informing that the new option should be included into this template.**

> **All _relevant_ items should be ticked before the PR is merged**

# Description

Adds an endpoint to the API for listing invites at `/user/invites`.

* All users get a response with `created`, `email`, `role`, `projects`
* Researchers can only list invites for projects where they are the owner
* Unit Admin|Personnel can list invites for the unit and any projects connected to the unit
* Superadmin can list all invites
  - Will also include a `unit` property 

Implements Jira Issue DDS-1353.

- [X] Add a summary of the changes and the related issue
- [ ] Add motivation and context regarding why the change is needed
- [ ] List / describe any dependencies or other changes required for this change
- [X] Fixes [link to issue / Jira issue ID]

## Type of change

- [ ] Documentation
- [ ] Workflow
- [ ] Security Alert fix
- [ ] Bug fix (non-breaking)
- [X] New feature (non-breaking)
- [ ] Breaking change (breaking, will cause existing functionality to not work as expected)
- [ ] Tests (only)

# Checklist:

## General

- [ ] [Changelog](../CHANGELOG.md): New row added. Not needed when PR includes _only_ tests.
- [ ] Database schema has changed
  - [ ] A new migration is included in the PR
  - [ ] The change does not require a migration
- [X] Code change
  - [X] Self-review of code done
  - [ ] Comments added, particularly in hard-to-understand areas
  - [ ] Documentation is updated

## Repository / Releases

- [ ] Blocking PRs have been merged
- [X] Rebase / update of branch done
- [ ] Product Owner / Scrum Master
  - [ ] The [version](../dds_web/version.py) is updated (PR to `master` branch)
  - [ ] I am bumping the major version (e.g. 1.x.x to 2.x.x)
    - [ ] I have made the corresponding changes to the CLI version

## Checks

- [ ] Formatting: Black & Prettier checks pass
- [ ] CodeQL passes
- [ ] Tests
  - [ ] I have added tests for the new code
  - [ ] The tests pass
- [ ] Trivy / Snyk:
  - [ ] There are no new security alerts
  - [ ] This PR fixes new security alerts
  - [ ] Security alerts have been dismissed
  - [ ] PR will be merged with new security alerts; This is why: _Please add a short description here_

2022-10-07 07:57 UTC, inaod568 requested changes
I'd like to add a check at the beginning of the endpoint too that raises an exception if the user is not a project owner in any ongoing projects. I think users will be confused otherwise regarding why they can't see any invites.

2022-10-07 07:57 UTC, inaod568 commented on dds_web/api/user.py
> +            unit_projects = set(proj.id for proj in owned_projects)
Slight simplification
```suggestion
            unit = current_user.unit
            unit_projects = set(proj.id for proj in unit.projects)
```

2022-10-07 07:57 UTC, inaod568 commented on dds_web/api/user.py
> +        out_model = ("email", "role", "created_at", "public_id")
Not used I think?

2022-10-07 07:57 UTC, inaod568 commented on dds_web/api/user.py
> +            for inv in raw_invites:
Add a little comment above this to explain for those that just want to skim and maybe understand less of the code

2022-10-07 07:57 UTC, inaod568 commented on dds_web/api/user.py
> +        key_map = {"email": "Email", "role": "Role", "created_at": "Created"}
Short comment above this next part too

2022-10-07 07:57 UTC, inaod568 commented on dds_web/api/user.py
> +            hits.append(hit)
Comment about what's done here

2022-10-10 08:02 UTC, inaod568 requested changes
I like the `row_to_dict` function. We need to add a little change though in order to clarify some of the info but otherwise 👍🏻 Also after this we need a test or two to verify

2022-10-10 08:08 UTC, talavis commented on dds_web/api/user.py
> +            hits = [row_to_dict(entry) for entry in models.Invite.query.all()]
It is added if the `Unit Admin` is adding the new `Unit *`. I think it makes sense to have projects shown as it immediately shows if more work will be needed once the person has been added to the unit.

2022-10-10 08:09 UTC, talavis commented on dds_web/api/user.py
> +            hits = [row_to_dict(entry) for entry in models.Invite.query.all()]
It can be skipped for superadmins, but I don't think it's a problem

2022-10-10 08:09 UTC, talavis commented on dds_web/api/user.py
> +                    hits.append(row_to_dict(inv))
This is not true if a new project is created while the invite is active, right?

2022-10-10 08:23 UTC, inaod568 commented on dds_web/api/user.py
> +            hits = [row_to_dict(entry) for entry in models.Invite.query.all()]
Never mind @talavis

2022-10-10 08:26 UTC, inaod568 commented on dds_web/api/user.py
> +                    hits.append(row_to_dict(inv))
Yes ignore this. https://github.com/ScilifelabDataCentre/dds_web/pull/1294#discussion_r991024561

2022-10-10 09:08 UTC, inaod568 commented
@talavis Can you rebase?

2022-10-10 09:43 UTC, inaod568 approved these changes
Looks good! Waiting for @valyo before merge.

2022-10-10 10:27 UTC, valyo approved these changes
Looks good and works as expected

2022-10-10 10:55 UTC, merged